In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("ce_setout_final_R.csv")

In [28]:
df

,Date,Time,Identifier,LineName,JobNumber,PONumber,SampleSize,cavity_identifier,DefectCode,DefectCount,Name
0,2021-11-03,21:30:00,1849d915-26c2-4fb1-b4a2-000183958622,J16,J19298,1022057,100,22bf2b29-6499-431d-92d4-3b611eb6db91,543,1,BREAKAGE
1,2021-11-03,21:30:00,1849d915-26c2-4fb1-b4a2-000183958622,J16,J19298,1022057,100,761c9653-dd85-44f9-a98d-905f2b01b112,543,1,BREAKAGE
2,2021-11-03,21:30:00,1849d915-26c2-4fb1-b4a2-000183958622,J16,J19298,1022057,100,0a338788-f21a-4a5d-a809-7c74d578ddaa,324,2,HEEL TAP
3,2021-11-03,21:30:00,1849d915-26c2-4fb1-b4a2-000183958622,J16,J19298,1022057,100,22bf2b29-6499-431d-92d4-3b611eb6db91,505,1,Bubble (>2.5 mm)
4,2021-11-03,21:30:00,1849d915-26c2-4fb1-b4a2-000183958622,J16,J19298,1022057,100,ad63c289-6eea-4f95-ad0a-f4c7622e7bc0,505,1,Bubble (>2.5 mm)
...,...,...,...,...,...,...,...,...,...,...,...
107535,2021-01-31,03:30:00,47a0a8cb-9535-4109-aa43-402222b0c9ed,J17,J18647,1021217,100,d7f2ba9b-9220-469c-8c6e-e13cbd010e3b,505,1,Bubble (>2.5 mm)
107536,2021-06-04,03:30:00,b86b4fd3-1e54-4f8d-ad6f-40261e38d3e2,J18,J20012,1022849,100,dccb5b53-8fc4-4b35-b509-4979f6784fbe,505,1,Bubble (>2.5 mm)
107537,2021-06-04,03:30:00,b86b4fd3-1e54-4f8d-ad6f-40261e38d3e2,J18,J20012,1022849,100,764819bb-e108-4e9a-9287-e584229b02df,505,1,Bubble (>2.5 mm)
107538,2021-06-04,03:30:00,b86b4fd3-1e54-4f8d-ad6f-40261e38d3e2,J18,J20012,1022849,100,f2969450-f7cf-4579-8011-da2141fd70a1,324,1,HEEL TAP
107539,2021-06-04,03:30:00,b86b4fd3-1e54-4f8d-ad6f-40261e38d3e2,J18,J20012,1022849,100,764819bb-e108-4e9a-9287-e584229b02df,102,1,PIN CRACK

In [29]:
df = df[df["LineName"] == "J13"]

In [19]:
df = df[df["Name"] == "Bubble (>2.5 mm)"]

In [30]:
df

,Date,Time,Identifier,LineName,JobNumber,PONumber,SampleSize,cavity_identifier,DefectCode,DefectCount,Name
177,2021-06-10,11:30:00,c09bce88-159c-4188-9d6f-001f73e9b8f1,J13,J23270,1024649,50,3187f537-ae36-4342-bf62-5f66f4eb8a7f,242,3,BLANK SEAM
185,2021-06-10,11:30:00,c09bce88-159c-4188-9d6f-001f73e9b8f1,J13,J23270,1024649,50,19dcfcea-d0ed-4f4c-a6fe-dc85cb53e18e,505,1,Bubble (>2.5 mm)
186,2021-06-10,11:30:00,c09bce88-159c-4188-9d6f-001f73e9b8f1,J13,J23270,1024649,50,7b391063-447e-40b1-99c7-5cc01eef8006,505,1,Bubble (>2.5 mm)
187,2021-06-10,11:30:00,c09bce88-159c-4188-9d6f-001f73e9b8f1,J13,J23270,1024649,50,c9e166ca-25e3-4577-8662-f7435ae97d38,505,1,Bubble (>2.5 mm)
188,2021-06-10,11:30:00,c09bce88-159c-4188-9d6f-001f73e9b8f1,J13,J23270,1024649,50,392e3470-4549-448d-b918-51e7ca731503,102,2,PIN CRACK
...,...,...,...,...,...,...,...,...,...,...,...
107445,2021-05-29,10:30:00,08977288-f440-46b2-840d-400eb7624c9a,J13,J20951,1023784,100,3f730c66-4d24-4e77-b337-8abed432735c,506,1,BLISTER
107446,2021-05-29,10:30:00,08977288-f440-46b2-840d-400eb7624c9a,J13,J20951,1023784,100,1643b9f7-dcca-47d8-8eb8-bef52f78e3ad,250,4,LOADING MARK
107447,2021-05-29,10:30:00,08977288-f440-46b2-840d-400eb7624c9a,J13,J20951,1023784,100,4df666b0-cd3e-432b-98bb-60f99587e54b,506,1,BLISTER
107448,2021-05-29,10:30:00,08977288-f440-46b2-840d-400eb7624c9a,J13,J20951,1023784,100,1643b9f7-dcca-47d8-8eb8-bef52f78e3ad,506,1,BLISTER
107461,2021-05-29,10:30:00,08977288-f440-46b2-840d-400eb7624c9a,J13,J20951,1023784,100,6f4db20f-7aa2-46f0-be16-83ddc03d74ab,505,1,Bubble (>2.5 mm)

In [10]:
df2 = df['Name'].value_counts()

In [25]:
df.to_csv("CE_Setout_J13.csv")

In [ ]:
df2 = df[]